#!/bin/bash
# This program uses two packages arp-scan and wakeonlan, both are required for this script to do WoL
# Use this program by invoking the program and placing the name johnny or hanz to invoke their respective MAC addresses

strComputerHardwareAddress=""

if [ "$1" == "johnny" ]
then
    strComputerHardwareAddress="00:00:00:00:00:00"
elif [ "$1" == "hanz" ]
then
    strComputerHardwareAddress="00:00:00:00:00:00"
fi

if [ "$strComputerHardwareAddress" != "" ]
then
    echo "Waking up $1 on $strComputerHardwareAddress, please wait 30 seconds for pc to wake up..."
    wakeonlan $strComputerHardwareAddress > /dev/null
    sleep 30
    strIp=$(arp-scan --interface=eth0 --localnet | grep $strComputerHardwareAddress | awk '{print $1}')
    if [ "$strIp" != "" ]
    then
        echo "Your IP is: $strIp"
    else
        echo "No IP found, try again later."
    fi
else
    echo "Failed to find a valid computer!"
fi