#!/bin/bash
# This program reads a file and for each line executes a reboot of a java solution
# This can be used in conjunction with SSH and cron to auto reboot instances with file drops
# Example of SSH: ssh -oStrictHostKeyChecking=no ubuntu@$ip 'echo $solution >> /home/ubuntu/solutions-rebootlist'

#Check if file exists
rebootListName='solutions-rebootlist'
rebootList="/home/ubuntu/$rebootListName"
if [ -f $rebootList ]
then
    #Check if reboot list is unoccupied by filesystem
    echo 'Check if file is unoccupied'
    while :
    do
        if ! lsof | grep $rebootListName
        then
            break
        fi
        sleep 1
    done

    #Read list of soltions to reboot and delete the file
    echo 'Reading solutions list'
    solutions=$(egrep -v '^[[:space:]]*$' $rebootList)
    rm -rf $rebootList
    
    #Run through reboot list and reboot solutions
    for solution in $solutions
    do
        echo "Stopping $solution"
        stop tomcat-$solution
        while :
        do
            echo "Waiting for $solution to shut down"
            if ! ps ax | grep java | grep $solution
            then
                break
            fi
            sleep 1
        done
        echo "Starting $solution"
        start tomcat-$solution
    done
fi